sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run travis-test

after_success:
  - "cat coverage/Firefox*/lcov.info | ./node_modules/.bin/coveralls"

branches:
  only:
    - develop
    - master
